### ISSUE TITLE
Problem with specific tag names.

### ISSUE THREAD

**Issue by ghost** [FerrahWolfeh/imageboard-downloader-rs#3]
Hello there, i'm trying to download "emilia_(re:zero)" tagged images from konachan, and it seems to not work because the filesystem doesn't support the ":" character in folder names.

**Comment by FerrahWolfeh** [comment]
Heya.

I tried patching that up. Try the latest `main` and see if it works correctly low

**Comment by ghost** [comment]
It works after the patch, i was able to get the downloads working, thanks.
